# Pytorch
Для более сложных моделей, например seq2seq, простого keras будет недостаточно. В основном, для этого используется PyTorch или Tensorflow. Здесь мы попытаемся разобрать основы работы с PyTorch. Для этого пройдемся по туториалам с официального сайта. Начнем с введения: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py    

## Установка
Если вам не нужна поддержка GPU или CUDA уже поставлена, то достаточно поставить с помощью команды, появляющейся после выбора соответвующией конфигурации: https://pytorch.org/get-started/locally/

Если же у вас Windows, то работает этот туториал:https://medium.com/@jjc7ru/one-stop-shop-for-all-your-windows-10-anaconda-pytorch-gpu-cuda10-setup-ad732fad67f1

С некоторыми модификациями:
- сейчас актуальная версия CUDA 10.1 - выбираем везде её
- При установке CUDA захочет Visual Studio, теоретически можно поставить и без неё, но лучше чтоб наверняка. С Visul Studio 2019 Community с установкой средств разработки для C++ все поставилось.

На Ubuntu CUDA вроде ставится из терминала, основная проблема - поставить драйвера.

Перейдем же наконец с самому PyTorch

In [2]:
import torch

## Тензоры
Для начала расссмотрим операции над тензорами

In [3]:
# Пустая матрица 5 на 3
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# Аналогично с рандомной инициализацией
x = torch.rand(5, 3)
print(x)

tensor([[0.4680, 0.8453, 0.2691],
        [0.8798, 0.4070, 0.7234],
        [0.4066, 0.0891, 0.0118],
        [0.6461, 0.8565, 0.0144],
        [0.2652, 0.2819, 0.8884]])


In [5]:
# Заполненная нулями и укзаным типом
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# Также можно конструировать тензоры из питонячих списков
x = torch.tensor([5.5, 3])
print(x) # тут увидим, что тип приаедтся

tensor([5.5000, 3.0000])


In [7]:
# Создание незоров, похожих на существуюшие 
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2037,  0.2799,  0.5992],
        [-0.2807, -0.6975,  1.4543],
        [ 1.4688, -0.0732,  2.4971],
        [-0.6484,  0.9008,  0.7525],
        [ 0.2666, -0.0824,  0.5907]])


Как мы видим инициализировать тензоры можно множеством способов и делается это вполне интуитивно.

## Операции
С тензорами можно проводить различные операции, причем также множеством способов. 

In [12]:
# Получения размерностей
print(x.size()) # можно взаимодействовать как с кортежем

# сложение
y = torch.rand(5,3)
print(y)
z1 = x + y
z2 = torch.add(x,y)
z3 = x.add(y)
# Все эти записи идентичты
print (torch.norm(z1- z2), torch.norm(z1 - z3), torch.norm(z2 -z3))

# Также есть модификация in-place
y.add_(x)
print(y)

# Ну и срезы тоже работают
print(y[:,1])

torch.Size([5, 3])
tensor([[0.7198, 0.0970, 0.1268],
        [0.8031, 0.9530, 0.3455],
        [0.1249, 0.6479, 0.2940],
        [0.3789, 0.2937, 0.2877],
        [0.2403, 0.0742, 0.7361]])
tensor(0.) tensor(0.) tensor(0.)
tensor([[ 0.9235,  0.3769,  0.7259],
        [ 0.5224,  0.2556,  1.7998],
        [ 1.5937,  0.5747,  2.7910],
        [-0.2695,  1.1945,  1.0402],
        [ 0.5068, -0.0082,  1.3268]])
tensor([ 0.3769,  0.2556,  0.5747,  1.1945, -0.0082])


Одним из самых частых операций при работе с сетями являлется изменение размерностей тензоров. Для этого существует базовая операция `view`, а также `transpose` - для транспонирования (view для этого не подойдет), `squeeze` - для удаления фиктивных размерностей и `unsqueeze` для их добавления.

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # в -1 перейдут оставшиейся размерности
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.rand(2,3)
print(x)
print(x.transpose(0,1))

x = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(x, 0))
y = torch.unsqueeze(x, 1)
print(y)
print(y.squeeze())

tensor([[0.6340, 0.6689, 0.8315],
        [0.8674, 0.0648, 0.8787]])
tensor([[0.6340, 0.8674],
        [0.6689, 0.0648],
        [0.8315, 0.8787]])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])


## Работа с NumPy
В PyTorch предусмотрены методы для создания тензоров из таковых в numpy и наоборот, из-за чего не нужно сильно запариваться с подготовкой данных, если та была сделана на numpy и использовалась, например, в keras

In [17]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

# также можно менять исходный тензор и тензор в numpy тоже изменится
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
# теперь в обратную сторону
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Тензоры
Тензоры могут быть перемещены с одного устройства на другое с помощью метода `to`

In [19]:
if torch.cuda.is_available(): # Проверяем что CUDA вообще есть
    device = torch.device("cuda")          # объявляем объект устройства
    y = torch.ones_like(x, device=device)  # создаем тензор прям на GPU
    x = x.to(device)                       # или переносим с помощью метода 'to'
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # 'to' можнт также менять тип

tensor([2, 3, 4, 5], device='cuda:0')
tensor([2., 3., 4., 5.], dtype=torch.float64)
